### ISSUE TITLE
Error parsing array literal with more than one string literal elements

### ISSUE THREAD

**Issue by libsteve** [mpw/Objective-Smalltalk#6]
```smalltalk
> #( 'a' ) do:[ :s | stdout println: s. ].
a
> #( 'a' 'b' ) do:[ :s | stdout println: s. ].
"invalid message in 'parseKeywordOrUnary' b/MPWStringLiteral from MPWStScanner with pos=10 probe=10 len=44, context='#( 'a' 'b''' ) do:[ '"
```

**Comment by mpw** [comment]
Yeah, sorry about that.  Objective-Smalltalk deviates from other Smalltalks in many details, one is that elements in array literals are separated by commas instead of whitespace, so the following will do the trick:

`> #( 'a' , 'b' ) do:[ :s | stdout println: s. ].`

More idiomatic would be to use a HOM:

`> stdout do println: #('a','b') each.`

**Comment by libsteve** [comment]
Great! Thanks for letting me know. You might want to update your site to reflect that, though http://objective.st/Examples/

**Comment by mpw** [comment]
Website has been updated.
